apiVersion: v1
kind: Pod
metadata:
        name: testapp
        labels:
                app: nodeapp
spec:
        containers:
                - name: nodeapp
                  image: 98ashish/nodeapp:1.0
                  ports:
                        - containerPort: 3000
